export const COMPANY_PHONE = "9466663015";
export const COMPANY_COUNTRY_CODE = "+91";
export const COMPANY_PHONE_E164 = `${COMPANY_COUNTRY_CODE}${COMPANY_PHONE}`;
export const COMPANY_PHONE_DISPLAY = `${COMPANY_COUNTRY_CODE} ${COMPANY_PHONE}`;
